apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Hello</title>
    <body>Run from RU-STAGE layer</body>
    </head>
    </html>