---
apiVersion: v1
kind: Service
metadata:
  name: api-test
  labels:
    app.kubernetes.io/name: api-test
spec:
  selector:
    app.kubernetes.io/name: api-test
  ports:
  - port: 80
    targetPort: http
    name: http
